### ISSUE TITLE
Issue on inserting 30 elements on a btree t=2 tree

### ISSUE THREAD

**Issue by pedronaresi** [seifertd/Ruby-BTree#2]
Hi Seifert! My name is Pedro. I'm using your code for a school project and I'm finding an error when insertion 30 elements on the tree. After the insertion, I can not query some elements, they simply disappear. Could u help me?

**Comment by seifertd** [comment]
Thanks for bringing this up. Buggy implementation for trees whose depth gets to large. I just checked in a fix, do you think you could try it ahead of me releasing it?

**Comment by pedronaresi** [comment]
Sure, trying it right now!
